## this network policy allows the startupapicheck to talk to the webhook
## i.e. startupapicheck can send requests to the webhook pod
{{- if .Values.webhook.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name:  {{ include "startupapicheck.name" . }}-allow-ingress
  namespace: {{ include "cert-manager.namespace" . }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector: {}
{{- end }}
